import "./globals.css";
import { DM_Sans } from "next/font/google";

import HeadBar from "@/components/HeadBar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Saas - be Productif",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`w-full min-h-screen overflow-x-hidden flex flex-col ${dmSans.className} `}
      >
        {<HeadBar />}
        {<Header />}
        {children}
        {<Footer />}
      </body>
    </html>
  );
}
